package Position;

public enum Position {

    FRONT_LEFT, FRONT_RIGHT, BACK_LEFT, BACK_RIGHT, FRONT_ROOF, BACK_ROOF, SIDE_RIGHT, SIDE_LEFT, FRONT_LEFT_ROOF, FRONT_RIGHT_ROOF, BACK_RIGHT_ROOF, FRONT;
}
